name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }} (${{ matrix.build_type }})
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
        - {
            name: "Windows MSVC 2019",
            os: windows-2019,
            cc: "cl",
            cxx: "cl",
            generator: "Visual Studio 16 2019"
          }
        - {
            name: "Windows MSVC 2022",
            os: windows-2022,
            cc: "cl",
            cxx: "cl",
            generator: "Visual Studio 17 2022"
          }
        - {
            name: "Ubuntu 20 GCC 9",
            os: ubuntu-20.04,
            cc: "gcc",
            cxx: "g++",
            generator: "Ninja"
          }
        - {
            name: "Ubuntu 22 GCC 11",
            os: ubuntu-22.04,
            cc: "gcc",
            cxx: "g++",
            generator: "Ninja"
          }
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    - name: Install Ninja (Linux)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Configure
      if: runner.os == 'Windows'
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: |
        cmake -B ${{github.workspace}}/build -G "${{ matrix.config.generator }}" -DCMAKE_BUILD_TYPE=${{matrix.build_type }} -A x64

    - name: Configure
      if: runner.os != 'Windows'
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: |
        cmake -B ${{github.workspace}}/build -G "${{ matrix.config.generator }}" -DCMAKE_BUILD_TYPE=${{matrix.build_type }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type }}
